realización de botón
raulcamano/proyecto-final pull request #7
Opened 2021-12-01 23:14 UTC by raulcamano

se añade fondos e imágenes

2021-12-02 00:16 UTC, abraham1669 requested changes

2021-12-02 00:16 UTC, abraham1669 commented on css/style.css
> +.body{
¿Se le agrego una clase body al body?

2021-12-02 00:16 UTC, abraham1669 commented on css/style.css
> +    src:url(../fons/Libre_Baskerville/LibreBaskerville-Bold.ttf);
Esto no funciona, no hay una regla css  que se llame src

2021-12-02 00:16 UTC, abraham1669 commented on css/style.css
> +    margin: 15px;
Esto sobre escribe el margin-top de arriba

2021-12-02 00:16 UTC, abraham1669 commented on css/style.css
> +
Esta línea en blanco sirve de algo?

2021-12-02 00:16 UTC, abraham1669 commented on css/style.css
> +    width: 10000px;
Esta propiedad está incorrecta

2021-12-02 00:16 UTC, abraham1669 commented on css/style.css
> +    height: 0px;
Este div no se está mostrando por esta propiedad

2021-12-02 00:16 UTC, abraham1669 commented on index.html
> +      margin-left: 1309px;"></div>
Eliminar los estilos en línea y añadirlos a una nueva clase

2021-12-02 00:16 UTC, abraham1669 commented on index.html
> +  <body class="part">
Este body no debe de existir, solo debe de existir un body por documento

2021-12-02 00:16 UTC, abraham1669 commented on index.html
> +    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
Esto es incorrecto, el script debe de ir antes de la etiqueta de cierre del body

2021-12-03 02:24 UTC, raulcamano commented on css/style.css
> +.body{
corrigiendo

2021-12-03 02:25 UTC, raulcamano commented on css/style.css
> +    src:url(../fons/Libre_Baskerville/LibreBaskerville-Bold.ttf);
entendido, se realiza el cambio

2021-12-03 02:25 UTC, raulcamano commented on css/style.css
> +    margin: 15px;
entendido, ya se cambia

2021-12-03 02:26 UTC, raulcamano commented on css/style.css
> +
no, me falto eliminar líneas en blanco

2021-12-03 02:26 UTC, raulcamano commented on css/style.css
> +    width: 10000px;
ok, corrigiendo

2021-12-03 02:27 UTC, raulcamano commented on css/style.css
> +    height: 0px;
ok, corrigiendo

2021-12-03 02:27 UTC, raulcamano commented on index.html
> +      margin-left: 1309px;"></div>
ok, corrigiendo

2021-12-03 02:27 UTC, raulcamano commented on index.html
> +  <body class="part">
ok, corrigiendo

2021-12-03 02:27 UTC, raulcamano commented on index.html
> +    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
ok, corrigiendo

2021-12-06 23:35 UTC, merged